services:
  app:
    container_name: attendance-management-system-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/src
    depends_on:
      - mysql

  web:
    container_name: attendance-management-system-web
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    container_name: attendance-management-system-mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_management_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: attendance-management-system-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - mysql

volumes:
  mysql-data:
